    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: urob
      url-base: https://github.com/urob	      url-base: https://github.com/urob
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:	  projects:
    - name: zmk	    - name: zmk
      remote: urob	      remote: infused-kim
      revision: main	      revision: pr-testing/mouse_ps2_v2
      import: app/west.yml	      import: app/west.yml
  self:	  self:
    path: config	    path: config
